#!/usr/bin/env python
#alter.py
from mcpi.minecraft import Minecraft
from mcpi import block
from time import sleep
from random import randint
import math
# ~ mc = Minecraft.create()	
mc = Minecraft.create("10.183.3.67", 4711)

def int():
    while 1==1:
        mc.postToChat("|POG    POG|")
        sleep(0.05)
        mc.postToChat("  |POG    POG|")
        sleep(0.05)
        mc.postToChat("    |POG    POG|")
        sleep(0.05)
        mc.postToChat("      |POG    POG|")
        sleep(0.05)
        mc.postToChat("        |POG    POG|")
        sleep(0.05)
        mc.postToChat("          |POG    POG|")
        sleep(0.05)
        mc.postToChat("            |POG    POG|")
        sleep(0.05)
        mc.postToChat("              |POG    POG|")
        sleep(0.05)
        mc.postToChat("                |POG    POG|")
        sleep(0.05)
        mc.postToChat("                 |POG    POG|")
        sleep(0.05)
        mc.postToChat("                    |POG    POG|")
        sleep(0.05)
        mc.postToChat("                     |POG    POG|")
        sleep(0.05)
        mc.postToChat("                        |POG    POG|")
        sleep(0.05)
        mc.postToChat("                         |POG    POG|")
        sleep(0.05)
        mc.postToChat("                            |POG    POG|")
        sleep(0.05)
        mc.postToChat("                             |POG    POG|")
        sleep(0.05)
        mc.postToChat("                                |POG    POG|")
        sleep(0.05)
        mc.postToChat("                                 |POG    POG|")
        sleep(0.05)
        mc.postToChat("                                    |POG    POG|")
        sleep(0.05)
        mc.postToChat("                                     |POG    POG")
        sleep(0.05)
        mc.postToChat("                                     |POG    POG")
        sleep(0.05)
        mc.postToChat("                                    |POG    POG|")
        sleep(0.05)
        mc.postToChat("                                  |POG    POG|")
        sleep(0.05)
        mc.postToChat("                                |POG    POG|")
        sleep(0.05)
        mc.postToChat("                              |POG    POG|")
        sleep(0.05)
        mc.postToChat("                            |POG    POG|")
        sleep(0.05)
        mc.postToChat("                          |POG    POG|")
        sleep(0.05)
        mc.postToChat("                        |POG    POG|")
        sleep(0.05)
        mc.postToChat("                      |POG    POG|")
        sleep(0.05)
        mc.postToChat("                    |POG    POG|")
        sleep(0.05)
        mc.postToChat("                  |POG    POG|")
        sleep(0.05)
        mc.postToChat("                |POG    POG|")
        sleep(0.05)
        mc.postToChat("              |POG    POG|")
        sleep(0.05)
        mc.postToChat("            |POG    POG|")
        sleep(0.05)
        mc.postToChat("          |POG    POG|")
        sleep(0.05)
        mc.postToChat("        |POG    POG|")
        sleep(0.05)
        mc.postToChat("      |POG    POG|")
        sleep(0.05)
        mc.postToChat("    |POG    POG|")
        sleep(0.05)
        mc.postToChat("  |POG    POG|")
        sleep(0.05)
        mc.postToChat("|POG    POG|")
        sleep(0.05)
    

int()
#10.183.3.9
